language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
before_install:
    # install prereqs
    - "cpanm Math::CDF"
    - "cpanm Devel::Cover::Report::Coveralls"
    - "cpanm Test::Most"
    - "cpanm Test::Exception"
script:
    perl Makefile.PL && make test && cover -test -report coveralls
